######################################################################
# Automatically generated by qmake (3.0) lun. juil. 8 00:03:07 2013
######################################################################

TEMPLATE = app
TARGET = SNalpha
INCLUDEPATH += .

# Input
HEADERS += MLP.h neurone.h
SOURCES += main.cpp MLP.cpp neurone.cpp
